name: "PlayEveryWare Unity Builder"
description: "Builds a Unity project"
inputs:
  pew-org-token:
    description: PlayEveryWare Organization access token
    required: true
runs:
  using: "composite"
  steps:
    - name: Ensure access token provided
      if: ${{ inputs.pew-org-token == '' }}
      run: |
        echo ::error::No PEW_ORG_TOKEN ${{ inputs.pew-org-token }} present in repository secrets
        exit 1
      shell: cmd

    - name: Get the private actions repository
      uses: actions/checkout@v3
      with:
        repository: PlayEveryWare/unity-build-private
        token: ${{ inputs.pew-org-token }}
        path: unity-build-private
        set-safe-directory: false

    - uses: ./unity-build-private
      with:
        pew-org-token: ${{ inputs.pew-org-token }}
