name: "PlayEveryWare Unity Builder"
description: "Builds a Unity project"
inputs:
  pew-org-token:
    description: PlayEveryWare Organization access token
    required: true
runs:
  using: "composite"
  steps:
    - name: Ensure access token provided
      if: ${{ inputs.pew-org-token == '' }}
      run: |
        echo ::error::No PEW_ORG_TOKEN ${{ inputs.pew-org-token }} present in repository secrets
        exit 1
      shell: cmd
