name: "PlayEveryWare Unity Builder"
description: "Builds a Unity project"
inputs:
  token:
    description: Github access token
    required: true
  pew-org-token:
    description: PlayEveryWare Organization access token
    required: true
runs:
  using: "composite"
  steps:
    - name: Ensure access token is provided
      if: ${{ inputs.token == '' }}
      shell: powershell
      run: |
        echo "::error::No TOKEN (token) passed to build action"
        exit 1

    - name: Ensure organization access token is provided
      if: ${{ inputs.pew-org-token == '' }}
      shell: powersheel
      run: |
        echo "::error::No Organization token (pew-build-token) passed to build action"
        exit 1

    - name: Get the private actions repository
      uses: actions/checkout@v3
      with:
        repository: PlayEveryWare/unity-build-private
        token: ${{ inputs.pew-org-token }}
        path: unity-build-private
        set-safe-directory: false

    - uses: ./unity-build-private
      with:
        token: ${{ inputs.token }}
        pew-org-token: ${{ inputs.pew-org-token }}
